# Generated by Django 6.1 on 2026-08-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_sellrprofile_sellerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readerprofile',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
