# Generated by Django 6.1 on 2026-08-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_fullname_readerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publisher', models.CharField(max_length=150)),
                ('publication_year', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('finance', 'Finance'), ('history', 'History'), ('biography', 'Biography'), ('science', 'Science'), ('technology', 'Technology'), ('self-help', 'Self Help'), ('romance', 'Romance'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Other', 'Other')], max_length=50)),
                ('page_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='myapp.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
