# Generated by Django 6.1 on 2026-08-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('specific_details', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_details', to='myapp.book')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_books', to='myapp.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeBookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='exchange_books/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='myapp.exchangebook')),
            ],
        ),
    ]
