# Generated by Django 6.0.7 on 2026-09-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_exchangebook_exchangebookphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
