# Generated by Django 6.0.7 on 2026-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_book_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='offer',
        ),
        migrations.AddField(
            model_name='book',
            name='offer_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
