# Generated by Django 6.1 on 2026-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_bookorder_address_and_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='delivery_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='tracking_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
