# Generated by Django 6.1 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookorder",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookorder",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not applicable"),
                    ("pending", "Refund pending"),
                    ("completed", "Refund completed"),
                ],
                default="not_applicable",
                max_length=20,
            ),
        ),
    ]