# Generated by Django 6.0.7 on 2026-09-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_webhookevent_bookorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangemessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
