# Generated by Django 6.0.7 on 2026-09-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_exchangemessage_is_read'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_book_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='exchange_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.exchangerequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('offer', 'New Offer'), ('chat', 'New Chat Message')], default='offer', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.book'),
        ),
    ]
