# Generated by Django 6.0.7 on 2026-09-19 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.bookorder'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('offer', 'New Offer'), ('chat', 'New Chat Message'), ('exchange_request', 'Exchange Request'), ('order', 'Order Update')], default='offer', max_length=20),
        ),
    ]
