# Generated by Django 6.0.7 on 2026-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_notification_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('offer', 'New Offer'), ('chat', 'New Chat Message'), ('exchange', 'Exchange Request')], default='offer', max_length=20),
        ),
    ]
