# Generated by Django 6.0.7 on 2026-09-20 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_notification_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemessage',
            name='exchange_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.exchangerequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('offer', 'New Offer'), ('chat', 'New Chat Message'), ('exchange', 'Exchange Request'), ('swap_proposal', 'Swap Proposal'), ('swap_accepted', 'Swap Accepted'), ('swap_declined', 'Swap Declined'), ('swap_completed', 'Swap Completed')], default='offer', max_length=20),
        ),
        migrations.CreateModel(
            name='SwapProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('exchange_method', models.CharField(choices=[('local', 'Local Handover'), ('shipping', 'Shipping'), ('either', 'Either')], default='either', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('confirmed', 'Confirmed'), ('handover_pending', 'Handover Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('received', 'Received'), ('completed', 'Completed')], default='sent', max_length=20)),
                ('requester_confirmed', models.BooleanField(default=False)),
                ('receiver_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('offered_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_swaps', to='myapp.book')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swap_proposals', to=settings.AUTH_USER_MODEL)),
                ('requested_exchange_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_proposals', to='myapp.exchangebook')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_swap_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='exchangemessage',
            name='swap_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.swapproposal'),
        ),
        migrations.AddField(
            model_name='notification',
            name='swap_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.swapproposal'),
        ),
    ]
