# Generated by Django 6.0.7 on 2026-09-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_exchangemessage_exchange_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangemessage',
            name='swap_proposal',
        ),
        migrations.RemoveField(
            model_name='swapproposal',
            name='receiver_confirmed',
        ),
        migrations.RemoveField(
            model_name='swapproposal',
            name='requester_confirmed',
        ),
        migrations.AddField(
            model_name='swapproposal',
            name='exchange_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_proposal', to='myapp.exchangerequest'),
        ),
        migrations.AlterField(
            model_name='exchangemessage',
            name='exchange_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.exchangerequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('offer', 'New Offer'), ('chat', 'New Chat Message'), ('exchange', 'Exchange Request'), ('swap_proposal', 'Swap Proposal')], default='offer', max_length=20),
        ),
        migrations.AlterField(
            model_name='swapproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('confirmed', 'Confirmed'), ('handover_pending', 'Handover Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('received', 'Received'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
