# Generated by Django 6.0.7 on 2026-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_exchangemessage_swap_proposal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='swap_proposal',
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='details_confirmed_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='details_confirmed_by_requester',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='owner_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='owner_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requester_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requester_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('details_confirmed', 'Details Confirmed'), ('ready_for_exchange', 'Ready for Exchange'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('offer', 'New Offer'), ('chat', 'New Chat Message'), ('exchange', 'Exchange Request')], default='offer', max_length=20),
        ),
        migrations.DeleteModel(
            name='SwapProposal',
        ),
    ]
