# Generated by Django 6.0.7 on 2026-09-21 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_notification_swap_proposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='details_confirmed_by_owner',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='details_confirmed_by_requester',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='owner_received_at',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='owner_sent_at',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='requester_received_at',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='requester_sent_at',
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='logistics_choice',
            field=models.CharField(blank=True, choices=[('meetup', 'Local Meetup'), ('shipping', 'Shipping')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='owner_condition_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='owner_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='owner_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='owner_tracking',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requester_condition_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requester_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requester_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requester_tracking',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('arranging', 'Arranging'), ('ready_to_exchange', 'Ready to Exchange'), ('in_transit', 'In Transit'), ('received', 'Received'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ExchangeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('not_received', 'Book not received'), ('condition_differs', 'Book condition differs'), ('wrong_book', 'Wrong book received'), ('damaged', 'Damaged during shipping'), ('unresponsive', 'User stopped responding'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='myapp.exchangerequest')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_exchange_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeMeetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('proposed_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('exchange_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meetup', to='myapp.exchangerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='myapp.exchangerequest')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchange_ratings', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_exchange_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
